runtime: java8
inbound_services:
- warmup
derived_file_type:
- java_precompiled
threadsafe: True
auto_id_policy: default
api_version: '1.0'
handlers:
- url: /
  script: unused
  login: optional
  secure: always
- url: /.*/
  script: unused
  login: optional
  secure: always
- url: /_ah/.*
  script: unused
  login: optional
  secure: always
- url: /.*\.jsp
  script: unused
  login: optional
  secure: always
- url: /init
  script: unused
  login: optional
  secure: always
- url: /hello
  script: unused
  login: optional
  secure: always
- url: .*\.jsp
  script: unused
  login: optional
  secure: optional
- url: /create
  script: unused
  login: optional
  secure: always

skip_files: app.yaml
